// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorials' }],
  guideSidebar: [{ type: 'autogenerated', dirName: 'guides' }],

  // Ha tényleg van docs/petstore mappád a repóban, akkor ez mehet:
  // petstoreSidebar: [{ type: 'autogenerated', dirName: 'petstore' }],
};

module.exports = sidebars;
