// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tutorials',
    },
  ],

  guideSidebar: [
    {
      type: 'autogenerated',
      dirName: 'guides',
    },
  ],
};

module.exports = sidebars;
