// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: 'tutorials' }],
  guideSidebar: [{ type: 'autogenerated', dirName: 'guides' }],

  // OpenAPI plugin által generált sidebar (ennek a fájlnak tényleg léteznie kell!)
  myApiSidebar: require('./docs/petstore/sidebar.js'),
};

module.exports = sidebars;
